### ISSUE TITLE
<h1><img> not showing the image

### ISSUE THREAD

**Issue by AzimLord** [m7mdra/HtmlRecylcer#4]
Hi guys, 

`<h1><img></img></h1>` not showing image

Maybe it checks the `<h1>` and try to render as `<h1>` instead of `<img>`

You guys know how to solve this issue?

**Comment by m7mdra** [comment]
`h1` is not supposed to be used as a container for other element and the library dose not support this.
You are welcome to create your own fork and modify it accordingly.

**Comment by AzimLord** [comment]
Alright. I'll try to figure something out
